version: '3.8'

services:
  db:
    container_name: app
    image: postgres:15
    volumes:
      - app:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

volumes:
  app:
